[workspace]
members = [
  "blocks-nats-to-sql",
  "database-maintenance",
  "dpplns",
  "earnings-to-balances",
  "event-scheduler",
  "nats_template",
  "shared", 
  "shares-to-pg",
  "stratum-nats-to-sql",
  "share-processor"
]